# Generated by Django 5.2.3 on 2025-08-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_mr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category in Marathi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Description in Marathi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name in Marathi'),
        ),
    ]
